spring.application.name=APIGATEWAY2
server.port=8085

eureka.client.service-url.defaultZone=http://localhost:8761/eureka
spring.cloud.discovery.enabled=true

# Product Service Route
spring.cloud.gateway.server.webflux.routes[0].id=product-service
spring.cloud.gateway.server.webflux.routes[0].uri=lb://ProductService
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/products/**

# User Service Route
spring.cloud.gateway.server.webflux.routes[1].id=order-service
spring.cloud.gateway.server.webflux.routes[1].uri=lb://OrderService
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/orders/**